### ISSUE TITLE
MG400 Connection refused

### ISSUE THREAD

**Issue by matheecs** [Dobot-Arm/MG400_ROS#1]
启动 `bringup.launch` 时终端打印 tcp recv error : 192.168.1.6 : 30003 connect : Connection refused，MG400拒绝连接，如何解决？

**Comment by monkeyrom** [comment]
I've got the same problem.

**Comment by matheecs** [comment]
> I've got the same problem.

**Comment by matheecs** [comment]
> I've got the same problem.

You need to contact their technical support to get the **new firmware** which can solve the problem.
